plone.recipe.codeanalysis now requires flake8>=2.4.0
~/git/rapido.plone(master)$ ./bin/buildout
[...]
The constraint, 2.3.0, is not consistent with the requirement, 'flake8>=2.4.0'.
While:
  Installing.
  Getting section code-analysis.
  Initializing section code-analysis.
  Installing recipe plone.recipe.codeanalysis.
Error: Bad constraint 2.3.0 flake8>=2.4.0